In [1]:
%load_ext autoreload

%autoreload 2
import sys
# sys.path.append('../mockportfolio/')
sys.path.append('../')
data_path = '../data/'
from mockportfolio import Holdings, Prices
holdings = Holdings(data_path)
prices = Prices(data_path)

In [21]:
import numpy as np
from empyrical import *
price_data = prices.get_prices()

tick_price = price_data[price_data.Tick == 'TNE']

# manual calc of returns
#tick_price['Returns'] = (tick_price.Close - tick_price.Close.shift(1)) / tick_price.Close.shift(1)

tick_price['Returns'] = simple_returns(tick_price.Close)
tick_price['CumReturns'] = cum_returns(tick_price.Returns)
display(tick_price)
print('returns', "{0:.0%}".format(annual_return(tick_price.Returns)))
print('drawdown', "{0:.0%}".format(max_drawdown(tick_price.Returns)))
print('sharpe', "{0:.0%}".format(sharpe_ratio(tick_price.Returns)))
print('volatility',  "{0:.0%}".format(annual_volatility(tick_price.Returns)))

d:\utils\anaconda3\envs\mockportfolio\lib\site-packages\ipykernel_launcher.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # Remove the CWD from sys.path while we load stuff.
d:\utils\anaconda3\envs\mockportfolio\lib\site-packages\ipykernel_launcher.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # This is added back by InteractiveShellApp.init_path()

,Date,Open,High,Low,Close,Adj Close,Volume,Tick,Returns,CumReturns
0,2018-01-22,4.86,4.90,4.810,4.840,4.739954,1357512.0,TNE,NaN,0.000000
1,2018-01-23,4.84,4.88,4.840,4.860,4.759541,569256.0,TNE,0.004132,0.004132
2,2018-01-24,4.93,4.95,4.820,4.850,4.749747,997811.0,TNE,-0.002058,0.002066
3,2018-01-25,4.86,4.98,4.805,4.980,4.877060,702785.0,TNE,0.026804,0.028926
4,2018-01-29,5.00,5.06,4.950,5.000,4.896646,909421.0,TNE,0.004016,0.033058
...,...,...,...,...,...,...,...,...,...,...
21091,2019-10-15,7.21,7.23,7.080,7.130,7.130000,764198.0,TNE,-0.016552,0.473140
21092,2019-10-16,7.25,7.38,7.185,7.330,7.330000,611171.0,TNE,0.028050,0.514463
21093,2019-10-17,7.31,7.40,7.210,7.230,7.230000,800391.0,TNE,-0.013643,0.493802
21094,2019-10-18,7.20,7.38,7.160,7.340,7.340000,1099727.0,TNE,0.015214,0.516529
22263,2019-10-21,7.35,7.42,7.280,7.375,7.375000,337400.0,TNE,0.004768,0.523760

returns 16%
drawdown -51%
sharpe 53%
volatility 54%